- hosts: all
  roles:
    - stage-output
  vars:
    stage_dir: "{{ ansible_user_dir }}/zuul-output"
    zuul_copy_output:
      '/opt/build/release': artifacts
      '/opt/build/build-*.log': logs_txt
